# Generated by Django 4.1.5 on 2023-02-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetranslation',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='coursetranslation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='coursetranslation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coursetranslation',
            name='price',
        ),
    ]
