# Generated by Django 4.1.5 on 2023-02-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_base_basetranslation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursetranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='coursetranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseTranslation',
        ),
    ]
