# Generated by Django 4.1.5 on 2023-02-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_coursetranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basetranslation',
            old_name='name',
            new_name='title',
        ),
    ]
