# Generated by Django 4.1.5 on 2023-02-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_name_basetranslation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetranslation',
            name='name_menu',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
