# Generated by Django 4.1.5 on 2023-02-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_menulevone_menulevtwo_basetranslation_menu_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulevtwotranslation',
            name='name_menu',
        ),
    ]
