# Generated by Django 4.1.5 on 2023-02-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_menulevonetranslation_menu_two_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basetranslation',
            name='menu_one',
        ),
        migrations.AddField(
            model_name='basetranslation',
            name='menu_one',
            field=models.ManyToManyField(blank=True, null=True, to='core.menulevone'),
        ),
    ]
