# Generated by Django 4.1.5 on 2023-02-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_basetranslation_menu_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetranslation',
            name='menu_one',
            field=models.ManyToManyField(blank=True, to='core.menulevone'),
        ),
        migrations.AlterField(
            model_name='menulevonetranslation',
            name='menu_two',
            field=models.ManyToManyField(blank=True, to='core.menulevtwo'),
        ),
    ]
