# Generated by Django 4.1.5 on 2023-02-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_basetranslation_menu_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulevtwotranslation',
            name='adress',
            field=models.CharField(default='#', max_length=90),
        ),
    ]
