# Generated by Django 4.1.5 on 2023-02-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_adress_menulevtwotranslation_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulevonetranslation',
            name='address',
            field=models.CharField(default='#', max_length=90),
        ),
    ]
