# Generated by Django 4.1.5 on 2023-01-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_email', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_line', models.CharField(max_length=256)),
                ('opening_message', models.CharField(max_length=256)),
                ('body_message', models.TextField()),
                ('closing_message', models.CharField(max_length=256)),
                ('signature_block', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='destination',
            name='email',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='destination',
            name='tag',
            field=models.CharField(max_length=256),
        ),
    ]
