# Generated by Django 4.1.5 on 2023-02-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_email', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
