# Generated by Django 4.1.7 on 2023-03-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('tag', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254, null=True)),
                ('subject_line', models.CharField(max_length=256)),
                ('opening_message', models.CharField(max_length=256)),
                ('body_message', models.TextField()),
                ('closing_message', models.CharField(max_length=256)),
                ('signature_block', models.CharField(max_length=256)),
            ],
        ),
    ]
